
import React from 'react';
import { Download, CheckCircle, FileText, ArrowLeft, Printer } from 'lucide-react';
import { MermaidChart } from './MermaidChart';

interface FinalReportProps {
    topic: string;
    goal: string;
    audience: string;
    finalContent: string;
    variableChart?: string;
    onBack: () => void;
}

export const FinalReport = ({ topic, goal, audience, finalContent, variableChart, onBack }: FinalReportProps) => {

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="min-h-screen bg-slate-100 py-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="max-w-4xl mx-auto bg-white shadow-2xl rounded-none sm:rounded-xl overflow-hidden print:shadow-none print:rounded-none">

                {/* Toolbar - Hidden when printing */}
                <div className="bg-slate-900 text-white p-4 flex justify-between items-center print:hidden">
                    <button onClick={onBack} className="flex items-center gap-2 text-slate-300 hover:text-white transition-colors">
                        <ArrowLeft size={18} /> Quay lại thảo luận
                    </button>
                    <div className="flex gap-3">
                        <button onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-sm font-medium transition-colors">
                            <Printer size={16} /> In / Lưu PDF
                        </button>
                        <button className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg text-sm font-medium transition-colors">
                            <Download size={16} /> Xuất Word (.docx)
                        </button>
                    </div>
                </div>

                {/* Report Content */}
                <div className="p-8 sm:p-12 md:p-16 max-w-[210mm] mx-auto bg-white min-h-[297mm]">
                    {/* Header Area */}
                    <div className="border-b-2 border-black pb-6 mb-8">
                        <div className="uppercase tracking-widest text-xs font-bold text-slate-500 mb-2">Báo Cáo Nghiên Cứu Khoa Học (Draft)</div>
                        <h1 className="text-3xl sm:text-4xl font-serif font-bold text-slate-900 leading-tight mb-4">
                            {topic}
                        </h1>
                        <div className="flex flex-wrap gap-6 text-sm text-slate-600 font-serif italic">
                            <div><strong>Mục tiêu:</strong> {goal}</div>
                            <div><strong>Độc giả:</strong> {audience}</div>
                            <div><strong>Ngày tạo:</strong> {new Date().toLocaleDateString('vi-VN')}</div>
                        </div>
                    </div>

                    {/* Model Visualization */}
                    {variableChart && (
                        <div className="mb-10 page-break-inside-avoid">
                            <h3 className="text-lg font-bold text-slate-900 mb-4 border-l-4 border-blue-600 pl-3 uppercase">
                                Mô Hình Nghiên Cứu Đề Xuất
                            </h3>
                            <MermaidChart chart={variableChart} />
                            <p className="text-center text-xs text-slate-500 italic mt-2">Hình 1. Sơ đồ mô hình nghiên cứu (Generated by AI)</p>
                        </div>
                    )}

                    {/* Main Content */}
                    <div className="prose prose-slate max-w-none font-serif prose-headings:font-sans prose-headings:font-bold prose-p:text-justify prose-a:text-blue-600">
                        {/* Simplified markdown rendering for demo - in prod use react-markdown */}
                        <div dangerouslySetInnerHTML={{ __html: finalContent.replace(/\n/g, '<br/>').replace(/# (.*?)\<br\/\>/g, '<h1>$1</h1>').replace(/## (.*?)\<br\/\>/g, '<h2>$1</h2>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }} />
                    </div>

                    {/* Footer */}
                    <div className="mt-20 pt-8 border-t border-slate-200 text-center text-xs text-slate-400">
                        <p>Tài liệu được tạo tự động bởi hệ thống <strong>Hải Debate AI</strong>.</p>
                        <p>Vui lòng kiểm tra lại tính chính xác trước khi sử dụng chính thức.</p>
                    </div>
                </div>
            </div>
        </div>
    );
};
